"""marketplace_professionals_briefs

Revision ID: 0292c377b6ed
Revises: d7e3a509c114
Create Date: 2026-08-23 16:32:56.027683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0292c377b6ed'
down_revision: Union[str, Sequence[str], None] = 'd7e3a509c114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('specializations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('service_areas', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('portfolio_images', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_project_id'), 'professionals', ['project_id'], unique=False)
    op.create_table('project_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_professional_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('budget_min', sa.Numeric(), nullable=False),
    sa.Column('budget_max', sa.Numeric(), nullable=False),
    sa.Column('budget_currency', sa.String(), nullable=False),
    sa.Column('timeline', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_briefs_project_id'), 'project_briefs', ['project_id'], unique=False)
    op.create_table('brief_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('professional_id', sa.String(), nullable=False),
    sa.Column('professional_name', sa.String(), nullable=False),
    sa.Column('proposed_fee', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timeline', sa.String(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('portfolio_items', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['project_briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_responses_project_id'), 'brief_responses', ['project_id'], unique=False)
    op.create_table('professional_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professional_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_reviews_project_id'), 'professional_reviews', ['project_id'], unique=False)
    op.drop_index(op.f('ix_boq_line_items_approved_vendor_id'), table_name='boq_line_items')
    op.drop_index(op.f('ix_boq_line_items_boq_id'), table_name='boq_line_items')
    op.drop_index(op.f('ix_boq_line_items_space_id'), table_name='boq_line_items')
    op.drop_constraint(op.f('fk_boq_line_items_boq_id'), 'boq_line_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_boq_line_items_space_id'), 'boq_line_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_boq_line_items_approved_vendor_id'), 'boq_line_items', type_='foreignkey')
    op.drop_index(op.f('ix_boqs_vendor_id'), table_name='boqs')
    op.drop_constraint(op.f('fk_boqs_vendor_id'), 'boqs', type_='foreignkey')
    op.drop_index(op.f('ix_decisions_domain_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_space_id'), table_name='decisions')
    op.drop_constraint(op.f('fk_decisions_space_id'), 'decisions', type_='foreignkey')
    op.drop_constraint(op.f('fk_decisions_domain_id'), 'decisions', type_='foreignkey')
    op.drop_index(op.f('ix_deliveries_purchase_order_id'), table_name='deliveries')
    op.drop_constraint(op.f('fk_deliveries_purchase_order_id'), 'deliveries', type_='foreignkey')
    op.drop_constraint(op.f('domains_project_id_slug_key'), 'domains', type_='unique')
    op.create_unique_constraint(None, 'domains', ['slug'])
    op.drop_index(op.f('ix_drawing_revisions_drawing_id'), table_name='drawing_revisions')
    op.drop_index(op.f('uq_drawing_revisions_drawing_code'), table_name='drawing_revisions')
    op.create_index(op.f('ix_drawing_revisions_project_id'), 'drawing_revisions', ['project_id'], unique=False)
    op.drop_constraint(op.f('fk_drawing_revisions_supersedes_id'), 'drawing_revisions', type_='foreignkey')
    op.drop_constraint(op.f('fk_drawing_revisions_drawing_id'), 'drawing_revisions', type_='foreignkey')
    op.drop_index(op.f('ix_drawings_domain_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_space_id'), table_name='drawings')
    op.drop_constraint(op.f('fk_drawings_space_id'), 'drawings', type_='foreignkey')
    op.drop_constraint(op.f('fk_drawings_domain_id'), 'drawings', type_='foreignkey')
    op.drop_index(op.f('ix_gallery_items_domain_id'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_space_id'), table_name='gallery_items')
    op.drop_constraint(op.f('fk_gallery_items_space_id'), 'gallery_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_gallery_items_domain_id'), 'gallery_items', type_='foreignkey')
    op.drop_index(op.f('ix_inspections_space_id'), table_name='inspections')
    op.drop_constraint(op.f('fk_inspections_space_id'), 'inspections', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_domain_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_space_id'), table_name='lessons')
    op.drop_constraint(op.f('fk_lessons_domain_id'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('fk_lessons_space_id'), 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_materials_vendor_id'), table_name='materials')
    op.drop_constraint(op.f('fk_materials_vendor_id'), 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_items_space_id'), table_name='procurement_items')
    op.drop_index(op.f('ix_procurement_items_vendor_id'), table_name='procurement_items')
    op.drop_constraint(op.f('fk_procurement_items_vendor_id'), 'procurement_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_procurement_items_space_id'), 'procurement_items', type_='foreignkey')
    op.drop_index(op.f('ix_progress_entries_space_id'), table_name='progress_entries')
    op.drop_constraint(op.f('fk_progress_entries_space_id'), 'progress_entries', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_quote_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_constraint(op.f('fk_purchase_orders_vendor_id'), 'purchase_orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_purchase_orders_quote_id'), 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_quote_line_items_boq_line_id'), table_name='quote_line_items')
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_constraint(op.f('fk_quote_line_items_boq_line_id'), 'quote_line_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_quote_line_items_quote_id'), 'quote_line_items', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_boq_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_vendor_id'), table_name='quotes')
    op.drop_constraint(op.f('fk_quotes_vendor_id'), 'quotes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotes_boq_id'), 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_snags_space_id'), table_name='snags')
    op.drop_constraint(op.f('fk_snags_space_id'), 'snags', type_='foreignkey')
    op.drop_constraint(op.f('spaces_project_id_slug_key'), 'spaces', type_='unique')
    op.create_unique_constraint(None, 'spaces', ['slug'])
    op.drop_index(op.f('ix_warranties_vendor_id'), table_name='warranties')
    op.drop_constraint(op.f('fk_warranties_vendor_id'), 'warranties', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_warranties_vendor_id'), 'warranties', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_warranties_vendor_id'), 'warranties', ['vendor_id'], unique=False)
    op.drop_constraint(None, 'spaces', type_='unique')
    op.create_unique_constraint(op.f('spaces_project_id_slug_key'), 'spaces', ['project_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_snags_space_id'), 'snags', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_snags_space_id'), 'snags', ['space_id'], unique=False)
    op.create_foreign_key(op.f('fk_quotes_boq_id'), 'quotes', 'boqs', ['boq_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotes_vendor_id'), 'quotes', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_quotes_vendor_id'), 'quotes', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_quotes_boq_id'), 'quotes', ['boq_id'], unique=False)
    op.create_foreign_key(op.f('fk_quote_line_items_quote_id'), 'quote_line_items', 'quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quote_line_items_boq_line_id'), 'quote_line_items', 'boq_line_items', ['boq_line_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_line_items_boq_line_id'), 'quote_line_items', ['boq_line_id'], unique=False)
    op.create_foreign_key(op.f('fk_purchase_orders_quote_id'), 'purchase_orders', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_purchase_orders_vendor_id'), 'purchase_orders', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_quote_id'), 'purchase_orders', ['quote_id'], unique=False)
    op.create_foreign_key(op.f('fk_progress_entries_space_id'), 'progress_entries', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_progress_entries_space_id'), 'progress_entries', ['space_id'], unique=False)
    op.create_foreign_key(op.f('fk_procurement_items_space_id'), 'procurement_items', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_procurement_items_vendor_id'), 'procurement_items', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_procurement_items_vendor_id'), 'procurement_items', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_procurement_items_space_id'), 'procurement_items', ['space_id'], unique=False)
    op.create_foreign_key(op.f('fk_materials_vendor_id'), 'materials', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_materials_vendor_id'), 'materials', ['vendor_id'], unique=False)
    op.create_foreign_key(op.f('fk_lessons_space_id'), 'lessons', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_lessons_domain_id'), 'lessons', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_lessons_space_id'), 'lessons', ['space_id'], unique=False)
    op.create_index(op.f('ix_lessons_domain_id'), 'lessons', ['domain_id'], unique=False)
    op.create_foreign_key(op.f('fk_inspections_space_id'), 'inspections', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_inspections_space_id'), 'inspections', ['space_id'], unique=False)
    op.create_foreign_key(op.f('fk_gallery_items_domain_id'), 'gallery_items', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_gallery_items_space_id'), 'gallery_items', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_gallery_items_space_id'), 'gallery_items', ['space_id'], unique=False)
    op.create_index(op.f('ix_gallery_items_domain_id'), 'gallery_items', ['domain_id'], unique=False)
    op.create_foreign_key(op.f('fk_drawings_domain_id'), 'drawings', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_drawings_space_id'), 'drawings', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_drawings_space_id'), 'drawings', ['space_id'], unique=False)
    op.create_index(op.f('ix_drawings_domain_id'), 'drawings', ['domain_id'], unique=False)
    op.create_foreign_key(op.f('fk_drawing_revisions_drawing_id'), 'drawing_revisions', 'drawings', ['drawing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_drawing_revisions_supersedes_id'), 'drawing_revisions', 'drawing_revisions', ['supersedes_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_drawing_revisions_project_id'), table_name='drawing_revisions')
    op.create_index(op.f('uq_drawing_revisions_drawing_code'), 'drawing_revisions', ['drawing_id', 'code'], unique=True)
    op.create_index(op.f('ix_drawing_revisions_drawing_id'), 'drawing_revisions', ['drawing_id'], unique=False)
    op.drop_constraint(None, 'domains', type_='unique')
    op.create_unique_constraint(op.f('domains_project_id_slug_key'), 'domains', ['project_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_deliveries_purchase_order_id'), 'deliveries', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_deliveries_purchase_order_id'), 'deliveries', ['purchase_order_id'], unique=False)
    op.create_foreign_key(op.f('fk_decisions_domain_id'), 'decisions', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_decisions_space_id'), 'decisions', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_decisions_space_id'), 'decisions', ['space_id'], unique=False)
    op.create_index(op.f('ix_decisions_domain_id'), 'decisions', ['domain_id'], unique=False)
    op.create_foreign_key(op.f('fk_boqs_vendor_id'), 'boqs', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_boqs_vendor_id'), 'boqs', ['vendor_id'], unique=False)
    op.create_foreign_key(op.f('fk_boq_line_items_approved_vendor_id'), 'boq_line_items', 'vendors', ['approved_vendor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_boq_line_items_space_id'), 'boq_line_items', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_boq_line_items_boq_id'), 'boq_line_items', 'boqs', ['boq_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_boq_line_items_space_id'), 'boq_line_items', ['space_id'], unique=False)
    op.create_index(op.f('ix_boq_line_items_boq_id'), 'boq_line_items', ['boq_id'], unique=False)
    op.create_index(op.f('ix_boq_line_items_approved_vendor_id'), 'boq_line_items', ['approved_vendor_id'], unique=False)
    op.drop_index(op.f('ix_professional_reviews_project_id'), table_name='professional_reviews')
    op.drop_table('professional_reviews')
    op.drop_index(op.f('ix_brief_responses_project_id'), table_name='brief_responses')
    op.drop_table('brief_responses')
    op.drop_index(op.f('ix_project_briefs_project_id'), table_name='project_briefs')
    op.drop_table('project_briefs')
    op.drop_index(op.f('ix_professionals_project_id'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
