"""initial_models

Revision ID: f5201d681403
Revises: 
Create Date: 2026-07-27 21:45:52.171597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5201d681403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('media_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subsections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_id', sa.String(), nullable=True),
    sa.Column('space_id', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_sets_domain_id'), 'media_sets', ['domain_id'], unique=False)
    op.create_index(op.f('ix_media_sets_project_id'), 'media_sets', ['project_id'], unique=False)
    op.create_index(op.f('ix_media_sets_space_id'), 'media_sets', ['space_id'], unique=False)
    op.drop_constraint(op.f('domains_project_id_slug_key'), 'domains', type_='unique')
    op.create_unique_constraint(None, 'domains', ['slug'])
    op.drop_constraint(op.f('spaces_project_id_slug_key'), 'spaces', type_='unique')
    op.create_unique_constraint(None, 'spaces', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spaces', type_='unique')
    op.create_unique_constraint(op.f('spaces_project_id_slug_key'), 'spaces', ['project_id', 'slug'])
    op.drop_constraint(None, 'domains', type_='unique')
    op.create_unique_constraint(op.f('domains_project_id_slug_key'), 'domains', ['project_id', 'slug'])
    op.drop_index(op.f('ix_media_sets_space_id'), table_name='media_sets')
    op.drop_index(op.f('ix_media_sets_project_id'), table_name='media_sets')
    op.drop_index(op.f('ix_media_sets_domain_id'), table_name='media_sets')
    op.drop_table('media_sets')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
