// AUTO-GENERATED by scripts/gen-renderings.ts — do not edit by hand.

export interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images: string[];
}

export const renderingsByDomain: Record<string, RenderingSet[]> = {
  "interior-design": [
    {
      "title": "Personal Spaces — Bedroom Interiors",
      "width": 1600,
      "height": 901,
      "images": [
        "/images/renderings/interior-design/bedroom-01.jpg",
        "/images/renderings/interior-design/bedroom-02.jpg",
        "/images/renderings/interior-design/bedroom-03.jpg",
        "/images/renderings/interior-design/bedroom-04.jpg",
        "/images/renderings/interior-design/bedroom-05.jpg",
        "/images/renderings/interior-design/bedroom-06.jpg",
        "/images/renderings/interior-design/bedroom-07.jpg",
        "/images/renderings/interior-design/bedroom-08.jpg",
        "/images/renderings/interior-design/bedroom-09.jpg",
        "/images/renderings/interior-design/bedroom-10.jpg",
        "/images/renderings/interior-design/bedroom-11.jpg",
        "/images/renderings/interior-design/bedroom-12.jpg",
        "/images/renderings/interior-design/bedroom-13.jpg",
        "/images/renderings/interior-design/bedroom-14.jpg",
        "/images/renderings/interior-design/bedroom-15.jpg",
        "/images/renderings/interior-design/bedroom-16.jpg",
        "/images/renderings/interior-design/bedroom-17.jpg",
        "/images/renderings/interior-design/bedroom-18.jpg",
        "/images/renderings/interior-design/bedroom-19.jpg",
        "/images/renderings/interior-design/bedroom-20.jpg",
        "/images/renderings/interior-design/bedroom-21.jpg",
        "/images/renderings/interior-design/bedroom-22.jpg",
        "/images/renderings/interior-design/bedroom-23.jpg",
        "/images/renderings/interior-design/bedroom-24.jpg",
        "/images/renderings/interior-design/bedroom-25.jpg",
        "/images/renderings/interior-design/bedroom-26.jpg",
        "/images/renderings/interior-design/bedroom-27.jpg",
        "/images/renderings/interior-design/bedroom-28.jpg",
        "/images/renderings/interior-design/bedroom-29.jpg",
        "/images/renderings/interior-design/bedroom-30.jpg",
        "/images/renderings/interior-design/bedroom-31.jpg"
      ]
    },
    {
      "title": "Ground & First Floor — Common Spaces",
      "width": 1600,
      "height": 901,
      "images": [
        "/images/renderings/interior-design/common-01.jpg",
        "/images/renderings/interior-design/common-02.jpg",
        "/images/renderings/interior-design/common-03.jpg",
        "/images/renderings/interior-design/common-04.jpg",
        "/images/renderings/interior-design/common-05.jpg",
        "/images/renderings/interior-design/common-06.jpg",
        "/images/renderings/interior-design/common-07.jpg",
        "/images/renderings/interior-design/common-08.jpg",
        "/images/renderings/interior-design/common-09.jpg",
        "/images/renderings/interior-design/common-10.jpg",
        "/images/renderings/interior-design/common-11.jpg",
        "/images/renderings/interior-design/common-12.jpg",
        "/images/renderings/interior-design/common-13.jpg",
        "/images/renderings/interior-design/common-14.jpg",
        "/images/renderings/interior-design/common-15.jpg",
        "/images/renderings/interior-design/common-16.jpg",
        "/images/renderings/interior-design/common-17.jpg",
        "/images/renderings/interior-design/common-18.jpg",
        "/images/renderings/interior-design/common-19.jpg",
        "/images/renderings/interior-design/common-20.jpg",
        "/images/renderings/interior-design/common-21.jpg",
        "/images/renderings/interior-design/common-22.jpg",
        "/images/renderings/interior-design/common-23.jpg"
      ]
    },
    {
      "title": "Multipurpose Room",
      "width": 1600,
      "height": 1131,
      "images": [
        "/images/renderings/interior-design/multipurpose-1.jpg",
        "/images/renderings/interior-design/multipurpose-2.jpg",
        "/images/renderings/interior-design/multipurpose-3.jpg",
        "/images/renderings/interior-design/multipurpose-4.jpg",
        "/images/renderings/interior-design/multipurpose-5.jpg",
        "/images/renderings/interior-design/multipurpose-6.jpg",
        "/images/renderings/interior-design/multipurpose-7.jpg",
        "/images/renderings/interior-design/multipurpose-8.jpg",
        "/images/renderings/interior-design/multipurpose-9.jpg"
      ]
    }
  ]
};
