/**
 * Regenerate data/renderings.ts from the converted PDF page images in
 * public/images/renderings/<domain>/. Run after adding/replacing renderings:
 *   npx tsx scripts/gen-renderings.ts
 *
 * Images are produced from the source PDFs in artifacts/renderings/ via:
 *   pdftoppm -jpeg -jpegopt quality=82 -scale-to 1600 "<deck>.pdf" "<out>/<key>"
 */
import { readdirSync, writeFileSync } from "node:fs";

interface DeckSpec {
  key: string; // filename prefix, e.g. "bedroom"
  title: string; // display heading
  width: number;
  height: number;
}

interface DomainSpec {
  slug: string;
  dir: string; // public path on disk (relative to repo root)
  publicPrefix: string; // URL prefix served by the site
  decks: DeckSpec[];
}

const DOMAINS: DomainSpec[] = [
  {
    slug: "interior-design",
    dir: "public/images/renderings/interior-design",
    publicPrefix: "/images/renderings/interior-design",
    decks: [
      { key: "bedroom", title: "Personal Spaces — Bedroom Interiors", width: 1600, height: 901 },
      { key: "common", title: "Ground & First Floor — Common Spaces", width: 1600, height: 901 },
      { key: "multipurpose", title: "Multipurpose Room", width: 1600, height: 1131 },
    ],
  },
];

const pageNo = (name: string): number => {
  const m = name.match(/-(\d+)\.jpg$/);
  return m ? Number.parseInt(m[1], 10) : 0;
};

const byDomain: Record<string, unknown[]> = {};

for (const domain of DOMAINS) {
  const files = readdirSync(domain.dir).filter((f) => f.endsWith(".jpg"));
  byDomain[domain.slug] = domain.decks.map((deck) => ({
    title: deck.title,
    width: deck.width,
    height: deck.height,
    images: files
      .filter((f) => f.startsWith(`${deck.key}-`))
      .sort((a, b) => pageNo(a) - pageNo(b))
      .map((f) => `${domain.publicPrefix}/${f}`),
  }));
}

const out = `// AUTO-GENERATED by scripts/gen-renderings.ts — do not edit by hand.

export interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images: string[];
}

export const renderingsByDomain: Record<string, RenderingSet[]> = ${JSON.stringify(
  byDomain,
  null,
  2,
)};
`;

writeFileSync("data/renderings.ts", out);
console.log("wrote data/renderings.ts");
