/**
 * Regenerate data/renderings.ts from the converted PDF page images in
 * public/images/renderings/<domain>/. Run after adding/replacing renderings:
 *   npx tsx scripts/gen-renderings.ts
 *
 * Images are produced from the source PDFs in artifacts/renderings/ via:
 *   pdftoppm -jpeg -jpegopt quality=82 -scale-to 1600 "<deck>.pdf" "<out>/<key>"
 *
 * The page→content mapping (cover / palette / room-divider slides) was read from
 * the source decks; section order and labels below are curated, not auto-derived.
 * Deck covers, room-title divider slides, and the "Thank you" slide are omitted —
 * each section gets its own heading instead.
 */
import { existsSync, writeFileSync } from "node:fs";

const PREFIX = "/images/renderings/interior-design";
const DISK = "public/images/renderings/interior-design";

/** Inclusive page range -> image paths. `pad` matches pdftoppm's zero-padding. */
const range = (key: string, from: number, to: number, pad: number): string[] => {
  const out: string[] = [];
  for (let n = from; n <= to; n++) {
    out.push(`${PREFIX}/${key}-${String(n).padStart(pad, "0")}.jpg`);
  }
  return out;
};

interface RenderingSubsection {
  title: string;
  images: string[];
}
interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images?: string[];
  subsections?: RenderingSubsection[];
}

const interiorDesign: RenderingSet[] = [
  {
    // 1. Common spaces first. Drop the deck cover (p01); keep palette + all views.
    title: "Ground & First Floor — Common Spaces",
    width: 1600,
    height: 901,
    images: range("common", 2, 23, 2),
  },
  {
    // 2. Bedrooms, reordered Master -> Elder -> Younger (deck order is reversed).
    title: "Personal Spaces — Bedroom Interiors",
    width: 1600,
    height: 901,
    subsections: [
      { title: "Master Bedroom", images: range("bedroom", 24, 30, 2) },
      { title: "Elder Daughter's Bedroom", images: range("bedroom", 13, 22, 2) },
      { title: "Younger Daughter's Bedroom", images: range("bedroom", 3, 11, 2) },
    ],
  },
  {
    // 3. Multipurpose room. Drop the deck cover (p01).
    title: "Multipurpose Room",
    width: 1600,
    height: 1131,
    images: range("multipurpose", 2, 9, 1),
  },
];

// Fail loudly if a curated range points at a missing image.
const allPaths = interiorDesign.flatMap((s) =>
  s.images ? s.images : (s.subsections ?? []).flatMap((sub) => sub.images),
);
const missing = allPaths.filter((p) => !existsSync(p.replace(PREFIX, DISK)));
if (missing.length) {
  console.error("Missing image files:\n" + missing.join("\n"));
  process.exit(1);
}

const byDomain = { "interior-design": interiorDesign };

const out = `// AUTO-GENERATED by scripts/gen-renderings.ts — do not edit by hand.

export interface RenderingSubsection {
  title: string;
  images: string[];
}

export interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images?: string[];
  subsections?: RenderingSubsection[];
}

export const renderingsByDomain: Record<string, RenderingSet[]> = ${JSON.stringify(
  byDomain,
  null,
  2,
)};
`;

writeFileSync("data/renderings.ts", out);
console.log(`wrote data/renderings.ts (${allPaths.length} images)`);
