/**
 * Regenerate data/renderings.ts from the converted PDF page images in
 * public/images/renderings/<domain>/. Run after adding/replacing renderings:
 *   npx tsx scripts/gen-renderings.ts
 *
 * Images are produced from the source PDFs in artifacts/renderings/ via:
 *   pdftoppm -jpeg -jpegopt quality=82 -scale-to 1600 "<deck>.pdf" "<out>/<key>"
 *
 * The page→content mapping (cover / palette / room-divider slides) was read from
 * the source decks; section order and labels below are curated, not auto-derived.
 * Deck covers, room-title divider slides, and the "Thank you" slide are omitted —
 * each section gets its own heading instead.
 */
import { existsSync, writeFileSync } from "node:fs";

const PREFIX = "/images/renderings/interior-design";
const LIGHT_PREFIX = "/images/renderings/lighting";
const FLOOR_PREFIX = "/images/renderings/flooring";

/**
 * Build an inclusive `key-from..to` page-range helper bound to one domain's
 * image prefix. `pad` matches pdftoppm's zero-padding.
 */
const ranger =
  (prefix: string) =>
  (key: string, from: number, to: number, pad: number): string[] => {
    const out: string[] = [];
    for (let n = from; n <= to; n++) {
      out.push(`${prefix}/${key}-${String(n).padStart(pad, "0")}.jpg`);
    }
    return out;
  };

const range = ranger(PREFIX);
const lrange = ranger(LIGHT_PREFIX);
const frange = ranger(FLOOR_PREFIX);

interface RenderingSubsection {
  title: string;
  images: string[];
}
interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images?: string[];
  subsections?: RenderingSubsection[];
}

const interiorDesign: RenderingSet[] = [
  {
    // 1. Common spaces first. Drop the deck cover (p01); keep palette + all views.
    title: "Ground & First Floor — Common Spaces",
    width: 1600,
    height: 901,
    images: range("common", 2, 23, 2),
  },
  {
    // 2. Bedrooms, reordered Master -> Elder -> Younger (deck order is reversed).
    title: "Personal Spaces — Bedroom Interiors",
    width: 1600,
    height: 901,
    subsections: [
      { title: "Master Bedroom", images: range("bedroom", 24, 30, 2) },
      { title: "Elder Daughter's Bedroom", images: range("bedroom", 13, 22, 2) },
      { title: "Younger Daughter's Bedroom", images: range("bedroom", 3, 11, 2) },
    ],
  },
  {
    // 3. Multipurpose room. Drop the deck cover (p01).
    title: "Multipurpose Room",
    width: 1600,
    height: 1131,
    images: range("multipurpose", 2, 9, 1),
  },
];

// Lighting Design Concept deck (artifacts/lighting-renderings/*.pdf). The deck
// walks each space as base view -> lighting diagram -> evening/relax/night
// scenes; we keep those house renders and drop the cover, inspiration, mood/
// reference/spec slides, room-title dividers and the "Thank you" slide. Pages
// are re-keyed per space into contiguous sequences (see scripts notes).
const lighting: RenderingSet[] = [
  {
    title: "Younger Daughter's Bedroom",
    width: 1600,
    height: 901,
    images: lrange("younger", 1, 4, 2),
  },
  {
    title: "Elder Daughter's Bedroom",
    width: 1600,
    height: 901,
    images: lrange("elder", 1, 5, 2),
  },
  {
    title: "Master Bedroom",
    width: 1600,
    height: 901,
    images: lrange("master", 1, 6, 2),
  },
  {
    title: "Common Spaces",
    width: 1600,
    height: 901,
    subsections: [
      { title: "Living Area", images: lrange("living", 1, 9, 2) },
      { title: "Kitchen & Dining", images: lrange("kitchen", 1, 4, 2) },
      { title: "First Floor Common Area", images: lrange("ff-common", 1, 5, 2) },
    ],
  },
  {
    title: "Exterior — Landscape & Facade",
    width: 1600,
    height: 901,
    images: lrange("exterior", 1, 16, 2),
  },
];

// Flooring Views deck (artifacts/flooring-views/designs/*.pdf). The deck walks
// the house floor by floor (Ground / Second / Terrace), each floor a key plan
// followed by ~24 "View N" flooring renders. We keep the renders and drop the
// cover, the three floor-plan key slides, the drainage diagram, plus exact
// duplicates and one unfinished frame. Pages are re-keyed per floor.
const flooring: RenderingSet[] = [
  {
    title: "Ground Floor",
    width: 1600,
    height: 901,
    images: frange("gf", 1, 23, 2),
  },
  {
    title: "Second Floor",
    width: 1600,
    height: 901,
    images: frange("sf", 1, 22, 2),
  },
  {
    title: "Terrace Floor",
    width: 1600,
    height: 901,
    images: frange("tf", 1, 28, 2),
  },
];

const byDomain = {
  "interior-design": interiorDesign,
  lighting,
  flooring,
};

// Fail loudly if a curated range points at a missing image.
const allPaths = Object.values(byDomain)
  .flat()
  .flatMap((s) =>
    s.images ? s.images : (s.subsections ?? []).flatMap((sub) => sub.images),
  );
const missing = allPaths.filter((p) => !existsSync(`public${p}`));
if (missing.length) {
  console.error("Missing image files:\n" + missing.join("\n"));
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/gen-renderings.ts — do not edit by hand.

export interface RenderingSubsection {
  title: string;
  images: string[];
}

export interface RenderingSet {
  title: string;
  width: number;
  height: number;
  images?: string[];
  subsections?: RenderingSubsection[];
}

export const renderingsByDomain: Record<string, RenderingSet[]> = ${JSON.stringify(
  byDomain,
  null,
  2,
)};
`;

writeFileSync("data/renderings.ts", out);
console.log(`wrote data/renderings.ts (${allPaths.length} images)`);
