#!/usr/bin/env bash
#
# Build the local Docker Postgres schema from scratch.
#
# Why this exists: the schema has two eras and neither half can build an empty DB alone.
#   - migrations/raw/001..004 create the 14 core tables, add the project_id tenant
#     column, media_sets and user_profiles.
#   - The Alembic tree was autogenerated LATER, against a DB that already had all of
#     that, so its "initial" revision f5201d681403 only adds constraints and assumes
#     `domains` already exists. `alembic upgrade head` on a bare DB fails.
# So: raw first, then stamp the Alembic base and upgrade to head.
#
# One ordering trap: raw/002 refuses to run unless projects already contains the
# backfill target 'proj-kr' (it would otherwise write a project_id that violates the FK
# it is about to add). The real row arrives with the seed, which runs after the schema
# exists — so a placeholder goes in here and the seed upserts over it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$ROOT/apps/api"
RAW="$API_DIR/migrations/raw"
psql_run() { docker compose -f "$ROOT/docker-compose.yml" exec -T db psql -v ON_ERROR_STOP=1 -U postgres "$@"; }

echo "==> raw/001_init.sql"
psql_run < "$RAW/001_init.sql" >/dev/null

echo "==> placeholder proj-kr (satisfies the 002 backfill guard)"
psql_run -c "INSERT INTO projects (id, public_title, public_subtitle, city, designer,
  direction, hero_image, concept_statement, internal_name, villa_no, community, address,
  plot_area, built_up_area, floors, status, start_date)
  VALUES ('proj-kr','','','','','','','','','','','','','',0,'','')
  ON CONFLICT (id) DO NOTHING;" >/dev/null

for f in 002_project_scope 003_media_sets 004_user_profiles; do
  echo "==> raw/$f.sql"
  psql_run < "$RAW/$f.sql" >/dev/null
done

echo "==> alembic stamp f5201d681403 && upgrade head"
cd "$API_DIR"
PYTHONPATH="$API_DIR" ./.venv/bin/python -m alembic stamp f5201d681403 >/dev/null
PYTHONPATH="$API_DIR" ./.venv/bin/python -m alembic upgrade head
echo "==> schema ready"
